import type { StatusDef } from './index';

/** Visite states V0–V7 (+ V5·C contestée, V✕ annulée) — run per occurrence. */
export const VISITE_STATES: StatusDef[] = [
  {
    code: 'added',
    level: 'V',
    num: 'V0',
    fr: 'À planifier',
    labels: { client: 'Visite à planifier', de9: 'Occurrence à planifier', pro: null },
    ball: 'de9',
    action: "Planifier l'occurrence",
    next: ['toConfirm'],
    actor: 'de9',
  },
  {
    code: 'toConfirm',
    level: 'V',
    num: 'V1',
    fr: 'À venir — à confirmer',
    labels: {
      client: 'Prochaine visite à confirmer : [date]',
      de9: 'En attente du client',
      pro: 'En attente de confirmation client',
    },
    ball: 'client',
    action: 'Confirmer la visite',
    next: ['confirmed', 'cancelled'],
    actor: 'client',
  },
  {
    code: 'confirmed',
    level: 'V',
    num: 'V2',
    fr: 'Confirmée — visite prévue',
    labels: {
      client: 'Prochaine visite : [date]',
      de9: 'Suivi de la visite',
      pro: 'Visite à venir — affecter',
    },
    ball: 'pro',
    action: 'Affecter un ou plusieurs ouvriers',
    next: ['confirmedAssigned', 'cancelled'],
    actor: 'pro',
  },
  {
    code: 'confirmedAssigned',
    level: 'V',
    num: 'V3',
    fr: 'Ouvrier affecté',
    labels: {
      client: 'Prochaine visite : [date]',
      de9: 'Visite à marquer réalisée',
      pro: 'Ouvrier(s) affecté(s) · visite à venir',
    },
    ball: 'de9',
    action: 'Marquer la visite réalisée',
    next: ['doneNoInvoice', 'cancelled'],
    actor: 'de9',
  },
  {
    code: 'doneNoInvoice',
    level: 'V',
    num: 'V4',
    fr: 'Réalisée — sans facture',
    labels: {
      client: 'En attente de la facture',
      de9: 'Suivi de la facture',
      pro: 'Facture à déposer',
    },
    ball: 'pro',
    action: 'Déposer la facture',
    next: ['doneInvoiced'],
    actor: 'pro',
  },
  {
    code: 'doneInvoiced',
    level: 'V',
    num: 'V5',
    fr: 'Facture déposée — à approuver',
    labels: {
      client: 'Facture à approuver',
      de9: 'En attente du client',
      pro: "En attente d'approbation",
    },
    ball: 'client',
    action: 'Approuver la facture',
    next: ['doneApproved', 'doneDisputed'],
    actor: 'client',
  },
  {
    code: 'doneDisputed',
    level: 'V',
    num: 'V5·C',
    fr: 'Facture contestée',
    labels: {
      client: 'Facture contestée',
      de9: 'Litige à résoudre',
      pro: 'Facture contestée',
    },
    ball: 'de9',
    action: 'Résoudre le litige',
    next: ['doneInvoiced'],
    actor: 'de9',
  },
  {
    code: 'doneApproved',
    level: 'V',
    num: 'V6',
    fr: 'Approuvée — à régler',
    labels: {
      client: 'Terminé',
      de9: 'Facture à régler',
      pro: 'Paiement en attente',
    },
    ball: 'de9',
    action: 'Régler (pro + prestataire)',
    next: ['paid'],
    actor: 'de9',
  },
  {
    code: 'paid',
    level: 'V',
    num: 'V7',
    fr: 'Payée — Terminé',
    labels: { client: 'Terminé', de9: 'Terminé', pro: 'Payé · Transféré' },
    ball: 'done',
    action: null,
    next: [],
    actor: null,
  },
  {
    code: 'cancelled',
    level: 'V',
    num: 'V✕',
    fr: 'Annulée',
    labels: { client: 'Annulée', de9: null, pro: null },
    ball: null,
    action: null,
    next: [],
    actor: null,
  },
];
